name: GIPHY generator

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
  issues_comment:
    types: [created, edited]
  
jobs:
  giphy-generator
    run-on: ubuntu-latest
  
    steps:
      - name: GIPHY Generator
        uses: IAmHughes/giphy-generator@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secret.GITHUB_TOKEN }}
          GIPHY_TOKEN: ${{ secret.GIPHY_TOKEN }}
        with:
          rating: 'g'
          lang: 'en'
